name: durg_rohak1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fort/Vasota.jpg
    - assets/fort/Torna.jpg
    - assets/fort/Rajgad_Fort.jpg
    - assets/fort/Harihar.jpg
    - assets/fort/devkunda.jpg
    - assets/fort/ratangad.jpg
